# Generated by Django 3.1.1 on 2021-09-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
