# Generated by Django 3.1.1 on 2021-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210920_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone_number', models.CharField(max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
