# Generated by Django 3.1.1 on 2021-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
