# Generated by Django 3.1.1 on 2021-09-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20210928_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
    ]
