# Generated by Django 3.1.1 on 2021-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_application_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
